//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Employee
    {
        public Employee()
        {
            this.Classes = new HashSet<Class>();
            this.Salaries = new HashSet<Salary>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string UserType { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime YearOfJoining { get; set; }
        public string Photo { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string LoginErrorMessage { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
