//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public string RegistrationNumber { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public string ModeOfPayment { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
