//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        public Hour()
        {
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public string HourId { get; set; }
        public string HourTime { get; set; }
    
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
