//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int EmployeeId { get; set; }
        public decimal Salary1 { get; set; }
        public int DaysAttended { get; set; }
        public int MonthId { get; set; }
        public string Year { get; set; }
        public System.DateTime RegisteredDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Month Month { get; set; }
    }
}
