//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Classes = new HashSet<Class>();
            this.Teachers = new HashSet<Teacher>();
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public string SubjectId { get; set; }
        public string SubjectName { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
